# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d7b4e6f86f09ae430a0cad3af7516bee600aed2ffebe3c912f2feeeb40ae11004c7735534c7696aa01eee3f149722701d28e53605f981c00ce4bbbc48fe419

test:
  secret_key_base: f9aa48b6e7ec5b200eb00ae0a6b534911240875dea8b2c5a238b45e3894dcf8470b7aec8ace154dc20ba2fcfb3127ec48ece564fa887199181ca10aba823d6b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
